// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {secretvault} from '../models';
import {main} from '../models';

export function AddSecret(arg1:string,arg2:string,arg3:string,arg4:string):Promise<secretvault.Meta>;

export function ApplyOnboardingString(arg1:string,arg2:string,arg3:boolean):Promise<main.OnboardingPreview>;

export function ApplyUpdate(arg1:string):Promise<string>;

export function CheckUpdate(arg1:string):Promise<main.UpdatePreview>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DisableTUN():Promise<void>;

export function EnableTUN():Promise<void>;

export function ExportOnboarding(arg1:string):Promise<string>;

export function ExportOnboardingQR(arg1:string):Promise<main.OnboardingQRResult>;

export function GetAdaptiveStatus():Promise<main.AdaptiveStatus>;

export function GetAutostart():Promise<boolean>;

export function GetDeliveryProfile():Promise<main.DeliveryProfile>;

export function GetFailoverStatus():Promise<main.FailoverStatus>;

export function GetMetrics():Promise<main.MetricsView>;

export function GetNetStats():Promise<main.NetStats>;

export function GetNetworkFacts():Promise<main.NetworkFacts>;

export function GetSplitDirect():Promise<Array<string>>;

export function GetState():Promise<main.AppState>;

export function IsTUNMode():Promise<boolean>;

export function ListChannels():Promise<Array<main.ChannelView>>;

export function ListSecrets():Promise<Array<secretvault.Meta>>;

export function ListTests():Promise<Array<main.TestResultView>>;

export function LoadOnboardingFile():Promise<string>;

export function NetGuardStatus():Promise<main.NetGuardStatus>;

export function OpenLogsDir():Promise<void>;

export function PickUpdateDir():Promise<string>;

export function PreviewOnboardingString(arg1:string,arg2:string):Promise<main.OnboardingPreview>;

export function RevealSecret(arg1:string):Promise<string>;

export function RunAdaptiveCheck():Promise<main.AdaptiveStatus>;

export function RunProbe():Promise<void>;

export function RunProxyHeal():Promise<boolean>;

export function RunTest(arg1:string):Promise<main.TestResultView>;

export function SaveOnboardingFile(arg1:string):Promise<string>;

export function SaveSecret(arg1:string,arg2:string):Promise<secretvault.Meta>;

export function SelectChannel(arg1:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function TailLogs():Promise<Array<main.LogLine>>;

export function TestSecret(arg1:string):Promise<main.SecretTestReport>;

export function VerifySecret(arg1:string):Promise<secretvault.Meta>;
