// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSecret'](arg1, arg2, arg3, arg4);
}

export function ApplyOnboardingString(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyOnboardingString'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DisableTUN() {
  return window['go']['main']['App']['DisableTUN']();
}

export function EnableTUN() {
  return window['go']['main']['App']['EnableTUN']();
}

export function ExportOnboarding(arg1) {
  return window['go']['main']['App']['ExportOnboarding'](arg1);
}

export function ExportOnboardingQR(arg1) {
  return window['go']['main']['App']['ExportOnboardingQR'](arg1);
}

export function GetAdaptiveStatus() {
  return window['go']['main']['App']['GetAdaptiveStatus']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetDeliveryProfile() {
  return window['go']['main']['App']['GetDeliveryProfile']();
}

export function GetFailoverStatus() {
  return window['go']['main']['App']['GetFailoverStatus']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetNetStats() {
  return window['go']['main']['App']['GetNetStats']();
}

export function GetNetworkFacts() {
  return window['go']['main']['App']['GetNetworkFacts']();
}

export function GetSplitDirect() {
  return window['go']['main']['App']['GetSplitDirect']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function IsTUNMode() {
  return window['go']['main']['App']['IsTUNMode']();
}

export function ListChannels() {
  return window['go']['main']['App']['ListChannels']();
}

export function ListSecrets() {
  return window['go']['main']['App']['ListSecrets']();
}

export function ListTests() {
  return window['go']['main']['App']['ListTests']();
}

export function LoadOnboardingFile() {
  return window['go']['main']['App']['LoadOnboardingFile']();
}

export function NetGuardStatus() {
  return window['go']['main']['App']['NetGuardStatus']();
}

export function OpenLogsDir() {
  return window['go']['main']['App']['OpenLogsDir']();
}

export function PickUpdateDir() {
  return window['go']['main']['App']['PickUpdateDir']();
}

export function PreviewOnboardingString(arg1, arg2) {
  return window['go']['main']['App']['PreviewOnboardingString'](arg1, arg2);
}

export function RevealSecret(arg1) {
  return window['go']['main']['App']['RevealSecret'](arg1);
}

export function RunAdaptiveCheck() {
  return window['go']['main']['App']['RunAdaptiveCheck']();
}

export function RunProbe() {
  return window['go']['main']['App']['RunProbe']();
}

export function RunProxyHeal() {
  return window['go']['main']['App']['RunProxyHeal']();
}

export function RunTest(arg1) {
  return window['go']['main']['App']['RunTest'](arg1);
}

export function SaveOnboardingFile(arg1) {
  return window['go']['main']['App']['SaveOnboardingFile'](arg1);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveSecret'](arg1, arg2);
}

export function SelectChannel(arg1) {
  return window['go']['main']['App']['SelectChannel'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TailLogs() {
  return window['go']['main']['App']['TailLogs']();
}

export function TestSecret(arg1) {
  return window['go']['main']['App']['TestSecret'](arg1);
}

export function VerifySecret(arg1) {
  return window['go']['main']['App']['VerifySecret'](arg1);
}
